module AdventOfCode
  module Puzzles2023
    module Day06
      class Race
        attr_reader time: Integer
        attr_reader distance: Integer
      end

      class Part1
        attr_reader races: Array[Race]

        def answer: () -> Integer

        def find_time_ranges: () -> Array[Range[Integer]]

        def parse_file: (String) -> void

        def parse_values: (Array[String], String) -> Array[Integer]

        def find_time_range: (Race) -> Range[Integer]

        def find_race_distance_times: (Race) -> Array[Float]

        def valid_time?: (Integer) -> bool
      end
    end
  end
end
