module AdventOfCode
  module Puzzles2023
    module Day04
      class Card
        attr_reader id: Integer
        attr_reader owned: Array[Integer]
        attr_reader winning: Array[Integer]
        attr_reader matches: Array[Integer]
      end

      class Part1
        attr_reader cards: Array[Card]

        def answer: () -> Integer

        def parse_cards: (Array[String]) -> void

        def points: () -> Array[Integer]
      end

      class Part2 < Part1
        def get_matching_cards: () -> Array[Card]

        def total_cards: () -> Array[ Hash[ Symbol, Card|Integer ] ]
      end
    end
  end
end
