module AdventOfCode
  module Puzzles2023
    module Day04
      class Card
        attr_reader id: Integer
        attr_reader owned: [Integer]
        attr_reader winning: [Integer]
        attr_reader matches: [Integer]
      end

      class Part1
        attr_reader cards: [Card]

        def answer: () -> Integer

        def parse_cards: ([String]) -> void

        def points: () -> [Integer]
      end

      class Part2 < Part1
        def get_matching_cards: () -> [Card]

        def total_cards: () -> [ { String: Card|Integer } ]
      end
    end
  end
end
