module AdventOfCode
  module Puzzles2023
    module Day01
      class Part1
        @calibration_values: [Integer]

        attr_reader file_contents: [String]

        def answer: () -> Integer

        def calibration_values: () -> [Integer]

        def find_first_number: () -> Integer?

        def find_last_number: () -> Integer?

        def select_number: (String) -> Integer
      end

      class Part2 < Part1
        TRANSLATIONS: { String: Integer }

        def translate_contents: () -> void

      end
    end
  end
end
