module AdventOfCode
  module Puzzles2023
    module Day02
      class Set
        attr_reader blue: Integer
        attr_reader green: Integer
        attr_reader red: Integer
        attr_reader power: Integer
      end

      class Game
        attr_reader id: Integer
        attr_reader sets: Array[Set]

        def valid?: (Integer, Integer, Integer) -> bool
      end

      class Part1
        attr_reader games: [Game]

        def answer: (Integer, Integer, Integer) -> Integer

        def load_games: (Array[String]) -> [Game]

        def parse_game_id: (String) -> Integer

        def parse_set: (String) -> Set

        def valid_games: (Integer, Integer, Integer) -> Array[Game]
      end

      class Part2 < Part1
        COLORS: Array[Symbol]

        attr_reader minimum_valid_sets: Hash[Game, Set]

        def minimum_valid_set_for: (Game) -> Set
      end
    end
  end
end
