module AdventOfCode
  module Puzzles2023
    module Day01
      class Part1
        attr_reader file_contents: Array[String]
        attr_reader calibration_values: Array[Integer]

        def answer: () -> Integer

        def find_first_number: () -> Integer?

        def find_last_number: () -> Integer?

        def select_number: (String) -> Integer
      end

      class Part2 < Part1
        TRANSLATIONS: Hash[String, Integer]

        def translate_contents: () -> void

      end
    end
  end
end
