module Puzzles
  module Day02
    class Part1Test
      def setup: -> untyped

      def teardown: -> untyped

      def test_answer_input_set: -> untyped

      def test_answer_test_data_set: -> untyped

      def test_valid_games_test_data_set: -> untyped
    end

    class Part2Test
      def setup: -> untyped

      def teardown: -> untyped

      def test_answer_input_set: -> untyped

      def test_answer_test_data_set: -> untyped

      def test_valid_games_test_data_set: -> untyped
    end
  end
end
