module Puzzles
  module Day03
    class Part1Test
      def setup: -> untyped

      def teardown: -> untyped

      def test_answer_input_set: -> untyped

      def test_answer_test_data_set: -> untyped

      def test_part_numbers_test_set: -> untyped
    end

    class Part2Test
      def setup: -> untyped

      def teardown: -> untyped

      def test_answer_input_set: -> untyped

      def test_answer_test_data_set: -> untyped

      def test_gears_test_set: -> untyped
    end
  end
end
