module AdventOfCode
  module Test
    module Puzzles2023
      module Day04
        class Part1Test
          def setup: -> untyped

          def teardown: -> untyped

          def test_points_test_data_set: -> untyped

          def test_answer_test_data_set: -> untyped

          def test_answer_input_set: -> untyped
        end

        class Part2Test
          def setup: -> untyped

          def teardown: -> untyped

          def test_total_cards_test_set: -> untyped

          def test_answer_test_data_set: -> untyped

          def test_answer_input_set: -> untyped
        end
      end
    end
  end
end
