module AdventOfCode
  module Test
    module Puzzles2023
      module Day01
        class Part1Test < MiniTest::Test
          def test_answer_real_set: -> untyped
          def test_answer_test_set: -> untyped
          def test_calibration_values_test_set: -> untyped
        end

        class Part2Test < MiniTest::Test
          def test_answer_real_set: -> untyped
          def test_answer_test_set: -> untyped
          def test_calibration_values_test_set: -> untyped
        end
      end
    end
  end
end
