module AdventOfCode
  module Test
    module Puzzles2024
      module Day04
        class Part1Test < MiniTest::Test
          def test_part1_answer_real_set: -> untyped
          def test_part1_answer_test_set: -> untyped
        end

        class Part2Test < MiniTest::Test
          def test_part2_answer_real_set: -> untyped
          def test_part2_answer_test_set: -> untyped
        end
      end
    end
  end
end
